/** TABLE USERS : NOUBLIE PAS DE REMETTRE LES MAILS EN INDEX **/

ALTER TABLE `announcements` CHANGE `IS_FULL_DAY_PRICE` `IS_FULL_DAY_PRICE` TINYINT( 1 ) NULL ;

ALTER TABLE `announcements` CHANGE `REGION_ID` `REGION_ID` VARCHAR( 3 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL ,
CHANGE `DEPARTMENT_ID` `DEPARTMENT_ID` VARCHAR( 3 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL ,
CHANGE `IS_PUBLISHED` `IS_PUBLISHED` TINYINT( 1 ) NULL ,
CHANGE `END_PUBLICATION_DATE` `END_PUBLICATION_DATE` DATE NULL ;

ALTER TABLE `announcement_prices` ADD `WEEK_END` FLOAT NULL AFTER `WEEK` ;

UPDATE `announcement_prices` SET WEEK_END =(SELECT DAY*2) WHERE WEEK_END IS NULL;

ALTER TABLE `announcement_reservations` ADD `DATE_END` DATE NULL AFTER `DATE` ;

UPDATE `announcement_reservations` SET DATE_END = (SELECT DATE) WHERE DATE_OPTION != 'period';

ALTER TABLE `announcement_reservations` ADD `CREATED_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ;
UPDATE `announcement_reservations` SET `CREATED_TIME` = NOW() ;