CREATE TABLE `tipkin-migration`.`feedbacks` (
`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`ANNOUNCE_ID` INT NOT NULL ,
`USER_OWNER_ID` INT NOT NULL ,
`USER_SUBSCRIBER_ID` INT NOT NULL ,
`USER_AUTHOR_ID` INT NOT NULL ,
`CREATION_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
`MARK` INT NOT NULL ,
`COMMENT` TEXT NOT NULL ;

/*AJOUT DE LA COLONNE CREATED TIME DANS lA TABLE USERS */

ALTER TABLE `announcement_reservations` ADD `UPDATED_TIME` TIMESTAMP NULL ,
ADD `ADMIN_PROCEED` BOOLEAN NOT NULL 